/* eslint-disable no-var, prefer-const */
/**
 * Auto-generated angle error model.
 *
 * Trained on: ai_shot_data_1770314167280.json
 * Features: cutAngle, spinY, power
 * Model: piecewise PolynomialFeatures(degree=3) + Ridge
 * Output clip: [-15, 15] degrees
 * Generated (UTC): 2026-02-06 08:18:42Z
 * Metrics (overall holdout test, random_state=42):
 *   rSquared: 0.718294
 *   rmse: 0.990989
 *   mae: 0.620376
 *
 * Generated by build_angle_model_nn.py
 */

// Bracket 0: power in [1.0, 2.0) (n=75, split=31, rmse=0.0451)
function __predictAngleError_b0_left(cutAngle, power) {
  return (
    0.00270063576 * 1.0 +
    0.0552636388868 * (cutAngle) +
    0.00270063575999 * (power) +
    6.12135307829e-05 * (Math.pow(cutAngle, 2)) +
    0.0552636388868 * (cutAngle * power) +
    0.00270063575999 * (Math.pow(power, 2)) +
    1.72488900086e-05 * (Math.pow(cutAngle, 3)) +
    6.12135356987e-05 * (Math.pow(cutAngle, 2) * power) +
    0.0552636388868 * (cutAngle * Math.pow(power, 2)) +
    0.00270063576 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b0_right(cutAngle, power) {
  return (
    0.0411125096323 * 1.0 +
    0.110310626782 * (cutAngle) +
    0.0411125096323 * (power) +
    -0.00320870575472 * (Math.pow(cutAngle, 2)) +
    0.11031062678 * (cutAngle * power) +
    0.0411125096323 * (Math.pow(power, 2)) +
    3.981609052e-05 * (Math.pow(cutAngle, 3)) +
    -0.00320870592153 * (Math.pow(cutAngle, 2) * power) +
    0.110310626777 * (cutAngle * Math.pow(power, 2)) +
    0.0411125096323 * (Math.pow(power, 3))
  );
}

// Bracket 1: power in [2.0, 3.0) (n=75, split=30, rmse=0.0296)
function __predictAngleError_b1_left(cutAngle, power) {
  return (
    3.49262153174e-06 * 1.0 +
    0.0077357295639 * (cutAngle) +
    7.04992123701e-06 * (power) +
    -1.64342474035e-05 * (Math.pow(cutAngle, 2)) +
    0.0156147133793 * (cutAngle * power) +
    1.42303966074e-05 * (Math.pow(power, 2)) +
    2.12939706267e-05 * (Math.pow(cutAngle, 3)) +
    -3.31728241038e-05 * (Math.pow(cutAngle, 2) * power) +
    0.0315185881164 * (cutAngle * Math.pow(power, 2)) +
    2.87243188976e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b1_right(cutAngle, power) {
  return (
    0.0257115530467 * 1.0 +
    0.00937495350632 * (cutAngle) +
    0.0518992459646 * (power) +
    -0.000794811130904 * (Math.pow(cutAngle, 2)) +
    0.0189235172647 * (cutAngle * power) +
    0.104759589076 * (Math.pow(power, 2)) +
    2.53361518441e-05 * (Math.pow(cutAngle, 3)) +
    -0.00160434068384 * (Math.pow(cutAngle, 2) * power) +
    0.0381974700673 * (cutAngle * Math.pow(power, 2)) +
    0.211459170544 * (Math.pow(power, 3))
  );
}

// Bracket 2: power in [3.0, 4.0) (n=150, split=31, rmse=0.0078)
function __predictAngleError_b2_left(cutAngle, power) {
  return (
    -2.42002880187e-06 * 1.0 +
    0.0017763939353 * (cutAngle) +
    -7.34971717408e-06 * (power) +
    -1.55567175467e-05 * (Math.pow(cutAngle, 2)) +
    0.00539497416962 * (cutAngle * power) +
    -2.23213632488e-05 * (Math.pow(power, 2)) +
    2.29616928625e-05 * (Math.pow(cutAngle, 3)) +
    -4.7246272948e-05 * (Math.pow(cutAngle, 2) * power) +
    0.0163847363764 * (cutAngle * Math.pow(power, 2)) +
    -6.77908066214e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b2_right(cutAngle, power) {
  return (
    0.00594076491539 * 1.0 +
    0.000270819299136 * (cutAngle) +
    0.0180423230758 * (power) +
    -5.52123507382e-05 * (Math.pow(cutAngle, 2)) +
    0.000822488258093 * (cutAngle * power) +
    0.0547952034125 * (Math.pow(power, 2)) +
    3.67863536762e-06 * (Math.pow(cutAngle, 3)) +
    -0.000167681430474 * (Math.pow(cutAngle, 2) * power) +
    0.0024979272596 * (cutAngle * Math.pow(power, 2)) +
    0.166415062237 * (Math.pow(power, 3))
  );
}

// Bracket 3: power in [4.0, 5.0) (n=188, split=29, rmse=0.0713)
function __predictAngleError_b3_left(cutAngle, power) {
  return (
    -4.7043854346e-07 * 1.0 +
    0.000586424837586 * (cutAngle) +
    -1.90788941296e-06 * (power) +
    -7.91424428512e-06 * (Math.pow(cutAngle, 2)) +
    0.00237827850958 * (cutAngle * power) +
    -7.73755256333e-06 * (Math.pow(power, 2)) +
    2.22207358032e-05 * (Math.pow(cutAngle, 3)) +
    -3.20966678295e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00964524060108 * (cutAngle * Math.pow(power, 2)) +
    -3.13800770764e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b3_right(cutAngle, power) {
  return (
    0.000973243812468 * 1.0 +
    0.000222049436965 * (cutAngle) +
    0.0039470443491 * (power) +
    -8.00683915349e-05 * (Math.pow(cutAngle, 2)) +
    0.000900533884846 * (cutAngle * power) +
    0.016007457642 * (Math.pow(power, 2)) +
    9.0378262797e-06 * (Math.pow(cutAngle, 3)) +
    -0.000324719869402 * (Math.pow(cutAngle, 2) * power) +
    0.00365216518667 * (cutAngle * Math.pow(power, 2)) +
    0.0649191337667 * (Math.pow(power, 3))
  );
}

// Bracket 4: power in [5.0, 6.0) (n=225, split=30, rmse=0.0515)
function __predictAngleError_b4_left(cutAngle, power) {
  return (
    -1.59089682779e-07 * 1.0 +
    0.000246810326461 * (cutAngle) +
    -8.07232217084e-07 * (power) +
    -6.44827066815e-06 * (Math.pow(cutAngle, 2)) +
    0.00125233387946 * (cutAngle * power) +
    -4.09595719119e-06 * (Math.pow(power, 2)) +
    2.32875784422e-05 * (Math.pow(cutAngle, 3)) +
    -3.2719196036e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00635443488899 * (cutAngle * Math.pow(power, 2)) +
    -2.07831819161e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b4_right(cutAngle, power) {
  return (
    0.00031373280391 * 1.0 +
    5.06632507233e-06 * (cutAngle) +
    0.00159190349216 * (power) +
    -1.91084213386e-06 * (Math.pow(cutAngle, 2)) +
    2.57068657639e-05 * (cutAngle * power) +
    0.0080774362298 * (Math.pow(power, 2)) +
    7.6956060439e-08 * (Math.pow(cutAngle, 3)) +
    -9.70035321502e-06 * (Math.pow(cutAngle, 2) * power) +
    0.000130438773254 * (cutAngle * Math.pow(power, 2)) +
    0.0409855096663 * (Math.pow(power, 3))
  );
}

// Bracket 5: power in [6.0, 7.0) (n=292, split=30, rmse=0.1921)
function __predictAngleError_b5_left(cutAngle, power) {
  return (
    -6.75174756449e-08 * 1.0 +
    0.00011809892527 * (cutAngle) +
    -4.11356994165e-07 * (power) +
    -8.63532784626e-06 * (Math.pow(cutAngle, 2)) +
    0.000719528638445 * (cutAngle * power) +
    -2.50623493784e-06 * (Math.pow(power, 2)) +
    2.81334763457e-05 * (Math.pow(cutAngle, 3)) +
    -5.26118221521e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00438379500181 * (cutAngle * Math.pow(power, 2)) +
    -1.5269394123e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b5_right(cutAngle, power) {
  return (
    0.000123353121409 * 1.0 +
    -4.5685655651e-05 * (cutAngle) +
    0.000751540311051 * (power) +
    3.33288480475e-05 * (Math.pow(cutAngle, 2)) +
    -0.000278344055521 * (cutAngle * power) +
    0.00457882903291 * (Math.pow(power, 2)) +
    -8.84006798228e-06 * (Math.pow(cutAngle, 3)) +
    0.000203040754672 * (Math.pow(cutAngle, 2) * power) +
    -0.00169583733148 * (cutAngle * Math.pow(power, 2)) +
    0.0278969401998 * (Math.pow(power, 3))
  );
}

// Bracket 6: power in [7.0, 8.0) (n=292, split=30, rmse=0.2802)
function __predictAngleError_b6_left(cutAngle, power) {
  return (
    -1.93308555725e-08 * 1.0 +
    6.26514423586e-05 * (cutAngle) +
    -1.3746387469e-07 * (power) +
    -4.29453372606e-06 * (Math.pow(cutAngle, 2)) +
    0.000445521359622 * (cutAngle * power) +
    -9.77523461469e-07 * (Math.pow(power, 2)) +
    2.60135186739e-05 * (Math.pow(cutAngle, 3)) +
    -3.05388868131e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00316815202291 * (cutAngle * Math.pow(power, 2)) +
    -6.95129762126e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b6_right(cutAngle, power) {
  return (
    4.49782393617e-05 * 1.0 +
    -1.25075814223e-05 * (cutAngle) +
    0.00031984528382 * (power) +
    9.46154850367e-06 * (Math.pow(cutAngle, 2)) +
    -8.89426167183e-05 * (cutAngle * power) +
    0.00227445532487 * (Math.pow(power, 2)) +
    -3.15691362563e-06 * (Math.pow(cutAngle, 3)) +
    6.72907286549e-05 * (Math.pow(cutAngle, 2) * power) +
    -0.000632482740939 * (cutAngle * Math.pow(power, 2)) +
    0.0161739035557 * (Math.pow(power, 3))
  );
}

// Bracket 7: power in [8.0, 9.0) (n=296, split=28, rmse=0.2515)
function __predictAngleError_b7_left(cutAngle, power) {
  return (
    6.39945153131e-09 * 1.0 +
    3.59878005336e-05 * (cutAngle) +
    5.20238108726e-08 * (power) +
    1.50172500981e-06 * (Math.pow(cutAngle, 2)) +
    0.00029256749353 * (cutAngle * power) +
    4.22929713287e-07 * (Math.pow(power, 2)) +
    1.75573315338e-05 * (Math.pow(cutAngle, 3)) +
    1.22084233187e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00237846535595 * (cutAngle * Math.pow(power, 2)) +
    3.43832514245e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b7_right(cutAngle, power) {
  return (
    1.49450984086e-05 * 1.0 +
    1.22216297573e-05 * (cutAngle) +
    0.000121498131757 * (power) +
    -1.58934985313e-05 * (Math.pow(cutAngle, 2)) +
    9.93573313543e-05 * (cutAngle * power) +
    0.000987734688126 * (Math.pow(power, 2)) +
    5.38857185991e-06 * (Math.pow(cutAngle, 3)) +
    -0.000129235671194 * (Math.pow(cutAngle, 2) * power) +
    0.000807738177782 * (cutAngle * Math.pow(power, 2)) +
    0.00802991755963 * (Math.pow(power, 3))
  );
}

// Bracket 8: power in [9.0, 10.0) (n=296, split=30, rmse=0.2922)
function __predictAngleError_b8_left(cutAngle, power) {
  return (
    1.17273120691e-08 * 1.0 +
    2.27476917926e-05 * (cutAngle) +
    1.07285833539e-07 * (power) +
    2.69853050717e-06 * (Math.pow(cutAngle, 2)) +
    0.000208099253901 * (cutAngle * power) +
    9.81448720576e-07 * (Math.pow(power, 2)) +
    1.48410756591e-05 * (Math.pow(cutAngle, 3)) +
    2.46871880329e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00190372268336 * (cutAngle * Math.pow(power, 2)) +
    8.97841808865e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b8_right(cutAngle, power) {
  return (
    1.07326218849e-05 * 1.0 +
    -8.00649817986e-06 * (cutAngle) +
    9.81835740868e-05 * (power) +
    1.28623199751e-05 * (Math.pow(cutAngle, 2)) +
    -7.32444144155e-05 * (cutAngle * power) +
    0.000898198047323 * (Math.pow(power, 2)) +
    -7.73429460137e-06 * (Math.pow(cutAngle, 3)) +
    0.000117706979636 * (Math.pow(cutAngle, 2) * power) +
    -0.000670055979424 * (cutAngle * Math.pow(power, 2)) +
    0.00821684886698 * (Math.pow(power, 3))
  );
}

// Bracket 9: power in [10.0, 11.0) (n=296, split=33, rmse=0.3122)
function __predictAngleError_b9_left(cutAngle, power) {
  return (
    8.32154587433e-08 * 1.0 +
    1.14355460006e-05 * (cutAngle) +
    8.46023299068e-07 * (power) +
    3.32098232383e-05 * (Math.pow(cutAngle, 2)) +
    0.000116261380802 * (cutAngle * power) +
    8.60122913288e-06 * (Math.pow(power, 2)) +
    -6.46039859193e-05 * (Math.pow(cutAngle, 3)) +
    0.000337632035 * (Math.pow(cutAngle, 2) * power) +
    0.0011819904755 * (cutAngle * Math.pow(power, 2)) +
    8.74460225256e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b9_right(cutAngle, power) {
  return (
    3.8723863901e-06 * 1.0 +
    5.48849886705e-06 * (cutAngle) +
    3.93692814103e-05 * (power) +
    -1.19434265066e-05 * (Math.pow(cutAngle, 2)) +
    5.57997209773e-05 * (cutAngle * power) +
    0.00040025440942 * (Math.pow(power, 2)) +
    7.85274521165e-06 * (Math.pow(cutAngle, 3)) +
    -0.000121406751406 * (Math.pow(cutAngle, 2) * power) +
    0.000567293852692 * (cutAngle * Math.pow(power, 2)) +
    0.00406925231284 * (Math.pow(power, 3))
  );
}

// Bracket 10: power in [11.0, 12.0) (n=296, split=28, rmse=0.2595)
function __predictAngleError_b10_left(cutAngle, power) {
  return (
    2.77965908101e-09 * 1.0 +
    1.01523485116e-05 * (cutAngle) +
    3.10913820658e-08 * (power) +
    1.58400415606e-06 * (Math.pow(cutAngle, 2)) +
    0.000113555906135 * (cutAngle * power) +
    3.47769565578e-07 * (Math.pow(power, 2)) +
    1.53311743838e-05 * (Math.pow(cutAngle, 3)) +
    1.77181463118e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00127014372838 * (cutAngle * Math.pow(power, 2)) +
    3.88970924348e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b10_right(cutAngle, power) {
  return (
    2.25487428031e-06 * 1.0 +
    3.226354414e-06 * (cutAngle) +
    2.52211777583e-05 * (power) +
    -7.33646310225e-06 * (Math.pow(cutAngle, 2)) +
    3.60868711914e-05 * (cutAngle * power) +
    0.000282103398486 * (Math.pow(power, 2)) +
    4.20162666695e-06 * (Math.pow(cutAngle, 3)) +
    -8.20528253921e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000403644315836 * (cutAngle * Math.pow(power, 2)) +
    0.00315538180674 * (Math.pow(power, 3))
  );
}

// Bracket 11: power in [12.0, 13.0) (n=296, split=27, rmse=0.6301)
function __predictAngleError_b11_left(cutAngle, power) {
  return (
    2.9285780983e-09 * 1.0 +
    6.93196754112e-06 * (cutAngle) +
    3.57410989546e-08 * (power) +
    3.1241123353e-06 * (Math.pow(cutAngle, 2)) +
    8.45957175094e-05 * (cutAngle * power) +
    4.36154887977e-07 * (Math.pow(power, 2)) +
    1.05234895263e-05 * (Math.pow(cutAngle, 3)) +
    3.81263920084e-05 * (Math.pow(cutAngle, 2) * power) +
    0.00103238063235 * (cutAngle * Math.pow(power, 2)) +
    5.32284731447e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b11_right(cutAngle, power) {
  return (
    8.15860379759e-07 * 1.0 +
    6.73006982803e-06 * (cutAngle) +
    9.95652881188e-06 * (power) +
    -1.88085357807e-05 * (Math.pow(cutAngle, 2)) +
    8.21326245766e-05 * (cutAngle * power) +
    0.000121506334125 * (Math.pow(power, 2)) +
    1.50865591433e-05 * (Math.pow(cutAngle, 3)) +
    -0.000229589012489 * (Math.pow(cutAngle, 2) * power) +
    0.00100233224597 * (cutAngle * Math.pow(power, 2)) +
    0.00148282558736 * (Math.pow(power, 3))
  );
}

// Bracket 12: power in [13.0, 14.0) (n=296, split=42, rmse=0.3328)
function __predictAngleError_b12_left(cutAngle, power) {
  return (
    3.5384504564e-08 * 1.0 +
    2.3736522353e-06 * (cutAngle) +
    4.67853577155e-07 * (power) +
    4.36568430325e-05 * (Math.pow(cutAngle, 2)) +
    3.13849036288e-05 * (cutAngle * power) +
    6.18613369014e-06 * (Math.pow(power, 2)) +
    -0.000166974293039 * (Math.pow(cutAngle, 3)) +
    0.000577232954582 * (Math.pow(cutAngle, 2) * power) +
    0.000414982247488 * (cutAngle * Math.pow(power, 2)) +
    8.17950596541e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b12_right(cutAngle, power) {
  return (
    1.28273796933e-06 * 1.0 +
    -2.70376529996e-06 * (cutAngle) +
    1.69606357217e-05 * (power) +
    5.35240958032e-06 * (Math.pow(cutAngle, 2)) +
    -3.57500004187e-05 * (cutAngle * power) +
    0.000224257509707 * (Math.pow(power, 2)) +
    -3.5684227753e-06 * (Math.pow(cutAngle, 3)) +
    7.07495287015e-05 * (Math.pow(cutAngle, 2) * power) +
    -0.000472695529049 * (cutAngle * Math.pow(power, 2)) +
    0.00296518010552 * (Math.pow(power, 3))
  );
}

// Bracket 13: power in [14.0, 15.0) (n=296, split=51, rmse=0.4633)
function __predictAngleError_b13_left(cutAngle, power) {
  return (
    -1.92051813757e-08 * 1.0 +
    4.24561323107e-06 * (cutAngle) +
    -2.73503816631e-07 * (power) +
    5.80362508642e-06 * (Math.pow(cutAngle, 2)) +
    6.04606289522e-05 * (cutAngle * power) +
    -3.894822502e-06 * (Math.pow(power, 2)) +
    -5.85601456537e-05 * (Math.pow(cutAngle, 3)) +
    8.26635815595e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000861005578433 * (cutAngle * Math.pow(power, 2)) +
    -5.54654568284e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b13_right(cutAngle, power) {
  return (
    -4.0050165004e-06 * 1.0 +
    4.57668761625e-05 * (cutAngle) +
    -5.70342650329e-05 * (power) +
    -0.000151543705475 * (Math.pow(cutAngle, 2)) +
    0.000651758611653 * (cutAngle * power) +
    -0.00081221037558 * (Math.pow(power, 2)) +
    0.000165430228342 * (Math.pow(cutAngle, 3)) +
    -0.00215820564657 * (Math.pow(cutAngle, 2) * power) +
    0.00928157976625 * (cutAngle * Math.pow(power, 2)) +
    -0.0115665042266 * (Math.pow(power, 3))
  );
}

// Bracket 14: power in [15.0, 16.0) (n=296, split=27, rmse=0.5444)
function __predictAngleError_b14_left(cutAngle, power) {
  return (
    7.90978120295e-10 * 1.0 +
    2.69127030129e-06 * (cutAngle) +
    1.2069600284e-08 * (power) +
    1.13304094693e-06 * (Math.pow(cutAngle, 2)) +
    4.10667714761e-05 * (cutAngle * power) +
    1.84176013963e-07 * (Math.pow(power, 2)) +
    1.88020800686e-05 * (Math.pow(cutAngle, 3)) +
    1.72897589013e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000626648879712 * (cutAngle * Math.pow(power, 2)) +
    2.81001702621e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b14_right(cutAngle, power) {
  return (
    3.46114261084e-07 * 1.0 +
    6.68492813338e-07 * (cutAngle) +
    5.28144879487e-06 * (power) +
    -4.52525991135e-06 * (Math.pow(cutAngle, 2)) +
    1.02006378336e-05 * (cutAngle * power) +
    8.05900464644e-05 * (Math.pow(power, 2)) +
    6.17941046853e-06 * (Math.pow(cutAngle, 3)) +
    -6.90983389955e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000155651691755 * (cutAngle * Math.pow(power, 2)) +
    0.00122975428591 * (Math.pow(power, 3))
  );
}

// Bracket 15: power in [16.0, 17.0) (n=296, split=27, rmse=0.8174)
function __predictAngleError_b15_left(cutAngle, power) {
  return (
    1.88107324345e-10 * 1.0 +
    2.09273633935e-06 * (cutAngle) +
    3.06364428388e-09 * (power) +
    2.29712283023e-06 * (Math.pow(cutAngle, 2)) +
    3.4065145917e-05 * (cutAngle * power) +
    4.98360131972e-08 * (Math.pow(power, 2)) +
    4.23615125511e-06 * (Math.pow(cutAngle, 3)) +
    3.73921183025e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000554504950989 * (cutAngle * Math.pow(power, 2)) +
    8.1119980692e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b15_right(cutAngle, power) {
  return (
    9.45114276507e-08 * 1.0 +
    3.03845874483e-06 * (cutAngle) +
    1.53845025308e-06 * (power) +
    -1.71771464912e-05 * (Math.pow(cutAngle, 2)) +
    4.94596239223e-05 * (cutAngle * power) +
    2.50423736872e-05 * (Math.pow(power, 2)) +
    2.83742208467e-05 * (Math.pow(cutAngle, 3)) +
    -0.000279566135446 * (Math.pow(cutAngle, 2) * power) +
    0.000805090465931 * (cutAngle * Math.pow(power, 2)) +
    0.000407634355054 * (Math.pow(power, 3))
  );
}

// Bracket 16: power in [17.0, 18.0) (n=296, split=48, rmse=0.4728)
function __predictAngleError_b16_left(cutAngle, power) {
  return (
    -3.06233354258e-09 * 1.0 +
    1.72988927461e-06 * (cutAngle) +
    -5.29575746362e-08 * (power) +
    7.12338013167e-06 * (Math.pow(cutAngle, 2)) +
    2.9920650551e-05 * (cutAngle * power) +
    -9.15880311547e-07 * (Math.pow(power, 2)) +
    -7.34853814877e-05 * (Math.pow(cutAngle, 3)) +
    0.000123206660007 * (Math.pow(cutAngle, 2) * power) +
    0.000517510785682 * (cutAngle * Math.pow(power, 2)) +
    -1.58389891052e-05 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b16_right(cutAngle, power) {
  return (
    7.17985119292e-07 * 1.0 +
    -7.73020148672e-06 * (cutAngle) +
    1.24184476584e-05 * (power) +
    3.5780029729e-05 * (Math.pow(cutAngle, 2)) +
    -0.000133706678819 * (cutAngle * power) +
    0.000214795641112 * (Math.pow(power, 2)) +
    -5.53399655553e-05 * (Math.pow(cutAngle, 3)) +
    0.000618885004345 * (Math.pow(cutAngle, 2) * power) +
    -0.00231265468887 * (cutAngle * Math.pow(power, 2)) +
    0.00371516762429 * (Math.pow(power, 3))
  );
}

// Bracket 17: power in [18.0, 19.0) (n=296, split=31, rmse=0.4396)
function __predictAngleError_b17_left(cutAngle, power) {
  return (
    1.33849011131e-09 * 1.0 +
    1.1719909022e-06 * (cutAngle) +
    2.45126965278e-08 * (power) +
    5.96037987196e-06 * (Math.pow(cutAngle, 2)) +
    2.14648106367e-05 * (cutAngle * power) +
    4.48939796521e-07 * (Math.pow(power, 2)) +
    -3.21179092289e-05 * (Math.pow(cutAngle, 3)) +
    0.000109163159515 * (Math.pow(cutAngle, 2) * power) +
    0.000393122135073 * (cutAngle * Math.pow(power, 2)) +
    8.22311622398e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b17_right(cutAngle, power) {
  return (
    1.95156493873e-07 * 1.0 +
    -1.34020779301e-06 * (cutAngle) +
    3.57432360436e-06 * (power) +
    8.22683448937e-06 * (Math.pow(cutAngle, 2)) +
    -2.45447946851e-05 * (cutAngle * power) +
    6.54634121662e-05 * (Math.pow(power, 2)) +
    -1.8258086946e-05 * (Math.pow(cutAngle, 3)) +
    0.000150696210381 * (Math.pow(cutAngle, 2) * power) +
    -0.00044954518386 * (cutAngle * Math.pow(power, 2)) +
    0.00119892512179 * (Math.pow(power, 3))
  );
}

// Bracket 18: power in [19.0, 20.0) (n=296, split=46, rmse=0.4098)
function __predictAngleError_b18_left(cutAngle, power) {
  return (
    -1.07610051234e-09 * 1.0 +
    9.47303375347e-07 * (cutAngle) +
    -2.08127416306e-08 * (power) +
    8.01414138482e-06 * (Math.pow(cutAngle, 2)) +
    1.83143333804e-05 * (cutAngle * power) +
    -4.02310486034e-07 * (Math.pow(power, 2)) +
    -9.51799988772e-05 * (Math.pow(cutAngle, 3)) +
    0.000154931507657 * (Math.pow(cutAngle, 2) * power) +
    0.000354078099563 * (cutAngle * Math.pow(power, 2)) +
    -7.77806241553e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b18_right(cutAngle, power) {
  return (
    -8.85021606988e-09 * 1.0 +
    1.9811898403e-06 * (cutAngle) +
    -1.71105455711e-07 * (power) +
    -1.52420401965e-05 * (Math.pow(cutAngle, 2)) +
    3.83031088826e-05 * (cutAngle * power) +
    -3.30758647141e-06 * (Math.pow(power, 2)) +
    3.54670671958e-05 * (Math.pow(cutAngle, 3)) +
    -0.000294567087216 * (Math.pow(cutAngle, 2) * power) +
    0.000740504544243 * (cutAngle * Math.pow(power, 2)) +
    -6.39446982311e-05 * (Math.pow(power, 3))
  );
}

// Bracket 19: power in [20.0, 21.0) (n=296, split=12, rmse=0.8795)
function __predictAngleError_b19_left(cutAngle, power) {
  return (
    3.31684732183e-10 * 1.0 +
    7.20275122446e-07 * (cutAngle) +
    6.75043035429e-09 * (power) +
    1.19810617801e-05 * (Math.pow(cutAngle, 2)) +
    1.46589315223e-05 * (cutAngle * power) +
    1.37384758534e-07 * (Math.pow(power, 2)) +
    -0.000291070388219 * (Math.pow(cutAngle, 3)) +
    0.000243836821762 * (Math.pow(cutAngle, 2) * power) +
    0.000298336433384 * (cutAngle * Math.pow(power, 2)) +
    2.79604724067e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b19_right(cutAngle, power) {
  return (
    -2.87123164574e-08 * 1.0 +
    2.34410158644e-06 * (cutAngle) +
    -5.84351176843e-07 * (power) +
    -1.93820445305e-05 * (Math.pow(cutAngle, 2)) +
    4.77132290758e-05 * (cutAngle * power) +
    -1.18934113133e-05 * (Math.pow(power, 2)) +
    4.73885418095e-05 * (Math.pow(cutAngle, 3)) +
    -0.000394562708793 * (Math.pow(cutAngle, 2) * power) +
    0.000971077845088 * (cutAngle * Math.pow(power, 2)) +
    -0.000242052381469 * (Math.pow(power, 3))
  );
}

// Bracket 20: power in [21.0, 22.0) (n=296, split=29, rmse=0.3418)
function __predictAngleError_b20_left(cutAngle, power) {
  return (
    4.21978665896e-10 * 1.0 +
    5.65013852914e-07 * (cutAngle) +
    9.01782948102e-09 * (power) +
    3.90584802784e-06 * (Math.pow(cutAngle, 2)) +
    1.20745396191e-05 * (cutAngle * power) +
    1.92726364411e-07 * (Math.pow(power, 2)) +
    -2.53430700932e-05 * (Math.pow(cutAngle, 3)) +
    8.34696345777e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000258037678827 * (cutAngle * Math.pow(power, 2)) +
    4.11820087232e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b20_right(cutAngle, power) {
  return (
    7.90713003711e-08 * 1.0 +
    -9.2291451865e-07 * (cutAngle) +
    1.68976528394e-06 * (power) +
    6.83906643745e-06 * (Math.pow(cutAngle, 2)) +
    -1.9723439272e-05 * (cutAngle * power) +
    3.61097468333e-05 * (Math.pow(power, 2)) +
    -1.99577389554e-05 * (Math.pow(cutAngle, 3)) +
    0.000146137649113 * (Math.pow(cutAngle, 2) * power) +
    -0.000421484114271 * (cutAngle * Math.pow(power, 2)) +
    0.000771704295268 * (Math.pow(power, 3))
  );
}

// Bracket 21: power in [22.0, 23.0) (n=296, split=28, rmse=0.9152)
function __predictAngleError_b21_left(cutAngle, power) {
  return (
    1.6208080572e-10 * 1.0 +
    5.44999637672e-07 * (cutAngle) +
    3.63335849288e-09 * (power) +
    2.3833359969e-06 * (Math.pow(cutAngle, 2)) +
    1.22019278544e-05 * (cutAngle * power) +
    8.12836630019e-08 * (Math.pow(power, 2)) +
    -7.23894601825e-06 * (Math.pow(cutAngle, 3)) +
    5.33604467044e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000273187437569 * (cutAngle * Math.pow(power, 2)) +
    1.82072307738e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b21_right(cutAngle, power) {
  return (
    4.18031301203e-08 * 1.0 +
    -8.28619625207e-08 * (cutAngle) +
    9.35979315303e-07 * (power) +
    4.24116634886e-07 * (Math.pow(cutAngle, 2)) +
    -1.85480028934e-06 * (cutAngle * power) +
    2.09556780766e-05 * (Math.pow(power, 2)) +
    -3.8222772202e-06 * (Math.pow(cutAngle, 3)) +
    9.54255155299e-06 * (Math.pow(cutAngle, 2) * power) +
    -4.15283187725e-05 * (cutAngle * Math.pow(power, 2)) +
    0.000469169461845 * (Math.pow(power, 3))
  );
}

// Bracket 22: power in [23.0, 24.0) (n=296, split=27, rmse=0.7650)
function __predictAngleError_b22_left(cutAngle, power) {
  return (
    5.56266316193e-11 * 1.0 +
    4.45459008688e-07 * (cutAngle) +
    1.30148852631e-09 * (power) +
    1.1176439441e-06 * (Math.pow(cutAngle, 2)) +
    1.04270269336e-05 * (cutAngle * power) +
    3.04561616731e-08 * (Math.pow(power, 2)) +
    6.63784182771e-06 * (Math.pow(cutAngle, 3)) +
    2.61609326358e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000244070628281 * (cutAngle * Math.pow(power, 2)) +
    7.12224547363e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b22_right(cutAngle, power) {
  return (
    3.01175276263e-08 * 1.0 +
    -1.59804864546e-08 * (cutAngle) +
    7.04967594691e-07 * (power) +
    -1.25662982769e-06 * (Math.pow(cutAngle, 2)) +
    -3.73538849004e-07 * (cutAngle * power) +
    1.65011336477e-05 * (Math.pow(power, 2)) +
    4.61010159657e-06 * (Math.pow(cutAngle, 3)) +
    -2.94399321029e-05 * (Math.pow(cutAngle, 2) * power) +
    -8.75933815039e-06 * (cutAngle * Math.pow(power, 2)) +
    0.000386259127387 * (Math.pow(power, 3))
  );
}

// Bracket 23: power in [24.0, 25.0) (n=296, split=28, rmse=1.1110)
function __predictAngleError_b23_left(cutAngle, power) {
  return (
    1.82646535245e-11 * 1.0 +
    3.8494537539e-07 * (cutAngle) +
    4.45512588415e-10 * (power) +
    6.79165308992e-08 * (Math.pow(cutAngle, 2)) +
    9.40266851939e-06 * (cutAngle * power) +
    1.07683487239e-08 * (Math.pow(power, 2)) +
    1.70191120242e-05 * (Math.pow(cutAngle, 3)) +
    1.65933922217e-06 * (Math.pow(cutAngle, 2) * power) +
    0.000229667724385 * (cutAngle * Math.pow(power, 2)) +
    2.66001607431e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b23_right(cutAngle, power) {
  return (
    4.2990208951e-08 * 1.0 +
    -8.35753385349e-07 * (cutAngle) +
    1.05004387415e-06 * (power) +
    9.24509157148e-06 * (Math.pow(cutAngle, 2)) +
    -2.04166616072e-05 * (cutAngle * power) +
    2.56476210598e-05 * (Math.pow(power, 2)) +
    -3.90777723132e-05 * (Math.pow(cutAngle, 3)) +
    0.000225743114434 * (Math.pow(cutAngle, 2) * power) +
    -0.000498665023681 * (cutAngle * Math.pow(power, 2)) +
    0.000626542919383 * (Math.pow(power, 3))
  );
}

// Bracket 24: power in [25.0, 26.0) (n=296, split=22, rmse=1.2353)
function __predictAngleError_b24_left(cutAngle, power) {
  return (
    -1.74597288286e-10 * 1.0 +
    3.96852749774e-07 * (cutAngle) +
    -4.44050650774e-09 * (power) +
    -5.22737936904e-06 * (Math.pow(cutAngle, 2)) +
    1.00977141199e-05 * (cutAngle * power) +
    -1.13056328331e-07 * (Math.pow(power, 2)) +
    0.000126484771955 * (Math.pow(cutAngle, 3)) +
    -0.000133007509388 * (Math.pow(cutAngle, 2) * power) +
    0.000256928760173 * (cutAngle * Math.pow(power, 2)) +
    -2.87503986539e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b24_right(cutAngle, power) {
  return (
    -4.09572154555e-09 * 1.0 +
    8.74617976029e-07 * (cutAngle) +
    -1.04227046678e-07 * (power) +
    -1.29348440793e-05 * (Math.pow(cutAngle, 2)) +
    2.22541850627e-05 * (cutAngle * power) +
    -2.65340284014e-06 * (Math.pow(power, 2)) +
    5.78515328135e-05 * (Math.pow(cutAngle, 3)) +
    -0.000329118381044 * (Math.pow(cutAngle, 2) * power) +
    0.000566302180583 * (cutAngle * Math.pow(power, 2)) +
    -6.75301068397e-05 * (Math.pow(power, 3))
  );
}

// Bracket 25: power in [26.0, 27.0) (n=296, split=31, rmse=0.8279)
function __predictAngleError_b25_left(cutAngle, power) {
  return (
    1.22923788062e-10 * 1.0 +
    2.81435715359e-07 * (cutAngle) +
    3.25341945507e-09 * (power) +
    2.49247509196e-06 * (Math.pow(cutAngle, 2)) +
    7.44766875564e-06 * (cutAngle * power) +
    8.60236115893e-08 * (Math.pow(power, 2)) +
    -2.95729496153e-05 * (Math.pow(cutAngle, 3)) +
    6.59586127059e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000197085521617 * (cutAngle * Math.pow(power, 2)) +
    2.27698820254e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b25_right(cutAngle, power) {
  return (
    2.2687078814e-08 * 1.0 +
    -3.5468500511e-07 * (cutAngle) +
    6.0034549355e-07 * (power) +
    4.68682930131e-06 * (Math.pow(cutAngle, 2)) +
    -9.38525459118e-06 * (cutAngle * power) +
    1.588916964e-05 * (Math.pow(power, 2)) +
    -2.16863845514e-05 * (Math.pow(cutAngle, 3)) +
    0.000124057955564 * (Math.pow(cutAngle, 2) * power) +
    -0.00024833773216 * (cutAngle * Math.pow(power, 2)) +
    0.000420414748784 * (Math.pow(power, 3))
  );
}

// Bracket 26: power in [27.0, 28.0) (n=296, split=46, rmse=1.0313)
function __predictAngleError_b26_left(cutAngle, power) {
  return (
    -1.73998307849e-10 * 1.0 +
    2.43476452342e-07 * (cutAngle) +
    -4.78287317692e-09 * (power) +
    3.60856191345e-06 * (Math.pow(cutAngle, 2)) +
    6.69142308714e-06 * (cutAngle * power) +
    -1.31315121275e-07 * (Math.pow(power, 2)) +
    -8.70050557047e-05 * (Math.pow(cutAngle, 3)) +
    9.91667273362e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000183879809906 * (cutAngle * Math.pow(power, 2)) +
    -3.6029452258e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b26_right(cutAngle, power) {
  return (
    -8.73180794183e-09 * 1.0 +
    8.51596289496e-07 * (cutAngle) +
    -2.40056294375e-07 * (power) +
    -1.33816268388e-05 * (Math.pow(cutAngle, 2)) +
    2.34020932538e-05 * (cutAngle * power) +
    -6.5967027459e-06 * (Math.pow(power, 2)) +
    6.71957924414e-05 * (Math.pow(cutAngle, 3)) +
    -0.000367681685196 * (Math.pow(cutAngle, 2) * power) +
    0.000643027592299 * (cutAngle * Math.pow(power, 2)) +
    -0.000181257923909 * (Math.pow(power, 3))
  );
}

// Bracket 27: power in [28.0, 29.0) (n=296, split=35, rmse=0.9352)
function __predictAngleError_b27_left(cutAngle, power) {
  return (
    4.19705463438e-10 * 1.0 +
    7.56563754137e-08 * (cutAngle) +
    1.1964580708e-08 * (power) +
    1.04450687492e-05 * (Math.pow(cutAngle, 2)) +
    2.15625784834e-06 * (cutAngle * power) +
    3.40926014306e-07 * (Math.pow(power, 2)) +
    -0.000179541869969 * (Math.pow(cutAngle, 3)) +
    0.000297684989088 * (Math.pow(cutAngle, 2) * power) +
    6.14550234367e-05 * (cutAngle * Math.pow(power, 2)) +
    9.7155090707e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b27_right(cutAngle, power) {
  return (
    -1.77637142633e-09 * 1.0 +
    6.20142756561e-07 * (cutAngle) +
    -5.06259263617e-08 * (power) +
    -1.19050027747e-05 * (Math.pow(cutAngle, 2)) +
    1.76744408004e-05 * (cutAngle * power) +
    -1.44302607128e-06 * (Math.pow(power, 2)) +
    6.94103661578e-05 * (Math.pow(cutAngle, 3)) +
    -0.000339216650849 * (Math.pow(cutAngle, 2) * power) +
    0.000503708200839 * (cutAngle * Math.pow(power, 2)) +
    -4.11164319185e-05 * (Math.pow(power, 3))
  );
}

// Bracket 28: power in [29.0, 30.0) (n=296, split=40, rmse=0.7116)
function __predictAngleError_b28_left(cutAngle, power) {
  return (
    3.32612311644e-10 * 1.0 +
    5.95905134416e-08 * (cutAngle) +
    9.8257175975e-09 * (power) +
    1.03992492901e-05 * (Math.pow(cutAngle, 2)) +
    1.75887271614e-06 * (cutAngle * power) +
    2.90469567836e-07 * (Math.pow(power, 2)) +
    -0.000198862003839 * (Math.pow(cutAngle, 3)) +
    0.000306970755704 * (Math.pow(cutAngle, 2) * power) +
    5.19104423396e-05 * (cutAngle * Math.pow(power, 2)) +
    8.56732082649e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b28_right(cutAngle, power) {
  return (
    -4.21397745145e-09 * 1.0 +
    5.90279720856e-07 * (cutAngle) +
    -1.24264430914e-07 * (power) +
    -1.07855258332e-05 * (Math.pow(cutAngle, 2)) +
    1.74222006281e-05 * (cutAngle * power) +
    -3.66954367409e-06 * (Math.pow(power, 2)) +
    6.13655808955e-05 * (Math.pow(cutAngle, 3)) +
    -0.00031812588818 * (Math.pow(cutAngle, 2) * power) +
    0.000514174812407 * (cutAngle * Math.pow(power, 2)) +
    -0.000108277809058 * (Math.pow(power, 3))
  );
}

// Bracket 29: power in [30.0, 31.0) (n=296, split=46, rmse=0.7279)
function __predictAngleError_b29_left(cutAngle, power) {
  return (
    -7.46052046972e-11 * 1.0 +
    1.36580847031e-07 * (cutAngle) +
    -2.27224161499e-09 * (power) +
    3.33592329041e-06 * (Math.pow(cutAngle, 2)) +
    4.17086274886e-06 * (cutAngle * power) +
    -6.96088203342e-08 * (Math.pow(power, 2)) +
    -0.000104419677124 * (Math.pow(cutAngle, 3)) +
    0.000101877638558 * (Math.pow(cutAngle, 2) * power) +
    0.000127358351013 * (cutAngle * Math.pow(power, 2)) +
    -2.10051070386e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b29_right(cutAngle, power) {
  return (
    4.90032763547e-08 * 1.0 +
    -1.99378177299e-06 * (cutAngle) +
    1.49648144352e-06 * (power) +
    2.78589653083e-05 * (Math.pow(cutAngle, 2)) +
    -6.08928487508e-05 * (cutAngle * power) +
    4.57015750504e-05 * (Math.pow(power, 2)) +
    -0.000129072003582 * (Math.pow(cutAngle, 3)) +
    0.000851619166807 * (Math.pow(cutAngle, 2) * power) +
    -0.00185938411531 * (cutAngle * Math.pow(power, 2)) +
    0.00139521995918 * (Math.pow(power, 3))
  );
}

// Bracket 30: power in [31.0, 32.0) (n=296, split=28, rmse=1.3723)
function __predictAngleError_b30_left(cutAngle, power) {
  return (
    3.68000828066e-11 * 1.0 +
    1.34191741715e-07 * (cutAngle) +
    1.16107991927e-09 * (power) +
    9.39742769035e-07 * (Math.pow(cutAngle, 2)) +
    4.23447180429e-06 * (cutAngle * power) +
    3.66597478579e-08 * (Math.pow(power, 2)) +
    1.6253858915e-06 * (Math.pow(cutAngle, 3)) +
    2.96553651696e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000133623264546 * (cutAngle * Math.pow(power, 2)) +
    1.15919370535e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b30_right(cutAngle, power) {
  return (
    6.67833780641e-09 * 1.0 +
    -1.01372193896e-07 * (cutAngle) +
    2.10885644397e-07 * (power) +
    1.253106728e-06 * (Math.pow(cutAngle, 2)) +
    -3.19837134014e-06 * (cutAngle * power) +
    6.65225506468e-06 * (Math.pow(power, 2)) +
    -9.77868397464e-06 * (Math.pow(cutAngle, 3)) +
    3.9539857866e-05 * (Math.pow(cutAngle, 2) * power) +
    -0.000100963766785 * (cutAngle * Math.pow(power, 2)) +
    0.000210058731753 * (Math.pow(power, 3))
  );
}

// Bracket 31: power in [32.0, 33.0) (n=296, split=28, rmse=1.0605)
function __predictAngleError_b31_left(cutAngle, power) {
  return (
    -3.40036276219e-11 * 1.0 +
    1.3225133557e-07 * (cutAngle) +
    -1.10704574261e-09 * (power) +
    -1.38473183574e-06 * (Math.pow(cutAngle, 2)) +
    4.30786675537e-06 * (cutAngle * power) +
    -3.59218212082e-08 * (Math.pow(power, 2)) +
    5.473157421e-05 * (Math.pow(cutAngle, 3)) +
    -4.51073768803e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000140330202979 * (cutAngle * Math.pow(power, 2)) +
    -1.17094547455e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b31_right(cutAngle, power) {
  return (
    2.73726182867e-09 * 1.0 +
    8.71719745996e-08 * (cutAngle) +
    8.93378569406e-08 * (power) +
    -2.97869498856e-06 * (Math.pow(cutAngle, 2)) +
    2.83972682233e-06 * (cutAngle * power) +
    2.91007541879e-06 * (Math.pow(power, 2)) +
    2.36819350425e-05 * (Math.pow(cutAngle, 3)) +
    -9.69561348846e-05 * (Math.pow(cutAngle, 2) * power) +
    9.2514951214e-05 * (cutAngle * Math.pow(power, 2)) +
    9.47933479075e-05 * (Math.pow(power, 3))
  );
}

// Bracket 32: power in [33.0, 34.0) (n=296, split=28, rmse=1.2255)
function __predictAngleError_b32_left(cutAngle, power) {
  return (
    -3.74296749882e-12 * 1.0 +
    1.10223429392e-07 * (cutAngle) +
    -1.24983538589e-10 * (power) +
    -4.87488198723e-08 * (Math.pow(cutAngle, 2)) +
    3.70264937668e-06 * (cutAngle * power) +
    -4.18761503229e-09 * (Math.pow(power, 2)) +
    2.06054679538e-05 * (Math.pow(cutAngle, 3)) +
    -1.63863206368e-06 * (Math.pow(cutAngle, 2) * power) +
    0.000124382449074 * (cutAngle * Math.pow(power, 2)) +
    -1.36485918519e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b32_right(cutAngle, power) {
  return (
    4.84007427062e-09 * 1.0 +
    -1.19344756854e-07 * (cutAngle) +
    1.62413718374e-07 * (power) +
    2.39268954254e-06 * (Math.pow(cutAngle, 2)) +
    -4.01037277889e-06 * (cutAngle * power) +
    5.45799983199e-06 * (Math.pow(power, 2)) +
    -2.06699638818e-05 * (Math.pow(cutAngle, 3)) +
    8.04293116641e-05 * (Math.pow(cutAngle, 2) * power) +
    -0.000134760568036 * (cutAngle * Math.pow(power, 2)) +
    0.000183538729027 * (Math.pow(power, 3))
  );
}

// Bracket 33: power in [34.0, 35.0) (n=296, split=29, rmse=1.2200)
function __predictAngleError_b33_left(cutAngle, power) {
  return (
    -1.30768194749e-11 * 1.0 +
    9.85258924746e-08 * (cutAngle) +
    -4.51075987911e-10 * (power) +
    -4.49496397091e-07 * (Math.pow(cutAngle, 2)) +
    3.41007083142e-06 * (cutAngle * power) +
    -1.56613367712e-08 * (Math.pow(power, 2)) +
    2.89156953996e-05 * (Math.pow(cutAngle, 3)) +
    -1.5557729598e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000118026779415 * (cutAngle * Math.pow(power, 2)) +
    -5.38620448781e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b33_right(cutAngle, power) {
  return (
    3.05849457357e-09 * 1.0 +
    -2.95286770332e-09 * (cutAngle) +
    1.0592659976e-07 * (power) +
    -1.21454919679e-06 * (Math.pow(cutAngle, 2)) +
    -1.02454955592e-07 * (cutAngle * power) +
    3.66344675365e-06 * (Math.pow(power, 2)) +
    1.22865235131e-05 * (Math.pow(cutAngle, 3)) +
    -4.20127131972e-05 * (Math.pow(cutAngle, 2) * power) +
    -3.49922076554e-06 * (cutAngle * Math.pow(power, 2)) +
    0.000126869807843 * (Math.pow(power, 3))
  );
}

// Bracket 34: power in [35.0, 36.0) (n=296, split=53, rmse=0.8575)
function __predictAngleError_b34_left(cutAngle, power) {
  return (
    -1.64916556384e-10 * 1.0 +
    1.20412120629e-07 * (cutAngle) +
    -5.91720343876e-09 * (power) +
    -1.16643590097e-06 * (Math.pow(cutAngle, 2)) +
    4.28872491753e-06 * (cutAngle * power) +
    -2.0956825008e-07 * (Math.pow(power, 2)) +
    -3.22584587993e-05 * (Math.pow(cutAngle, 3)) +
    -4.15663013664e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000152819086075 * (cutAngle * Math.pow(power, 2)) +
    -7.46893427897e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b34_right(cutAngle, power) {
  return (
    6.50698626199e-08 * 1.0 +
    -3.65249344589e-06 * (cutAngle) +
    2.31789673559e-06 * (power) +
    6.92013806207e-05 * (Math.pow(cutAngle, 2)) +
    -0.000130167241108 * (cutAngle * power) +
    8.26102545311e-05 * (Math.pow(power, 2)) +
    -0.000441275066489 * (Math.pow(cutAngle, 3)) +
    0.00246504604581 * (Math.pow(cutAngle, 2) * power) +
    -0.00463771632973 * (cutAngle * Math.pow(power, 2)) +
    0.00294327503152 * (Math.pow(power, 3))
  );
}

// Bracket 35: power in [36.0, 37.0) (n=296, split=51, rmse=0.9392)
function __predictAngleError_b35_left(cutAngle, power) {
  return (
    -1.13530953245e-10 * 1.0 +
    1.00639815624e-07 * (cutAngle) +
    -4.17520577221e-09 * (power) +
    -3.69391877696e-07 * (Math.pow(cutAngle, 2)) +
    3.68801106265e-06 * (cutAngle * power) +
    -1.52922690113e-07 * (Math.pow(power, 2)) +
    -4.56104964357e-05 * (Math.pow(cutAngle, 3)) +
    -1.35480701087e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000135142311921 * (cutAngle * Math.pow(power, 2)) +
    -5.57338447645e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b35_right(cutAngle, power) {
  return (
    -4.10256496616e-09 * 1.0 +
    3.98812753677e-07 * (cutAngle) +
    -1.50569200142e-07 * (power) +
    -9.65061875248e-06 * (Math.pow(cutAngle, 2)) +
    1.46166015209e-05 * (cutAngle * power) +
    -5.51380621371e-06 * (Math.pow(power, 2)) +
    6.94360175776e-05 * (Math.pow(cutAngle, 3)) +
    -0.000354135601076 * (Math.pow(cutAngle, 2) * power) +
    0.000535691491165 * (cutAngle * Math.pow(power, 2)) +
    -0.00020216489088 * (Math.pow(power, 3))
  );
}

// Bracket 36: power in [37.0, 38.0) (n=296, split=50, rmse=1.5071)
function __predictAngleError_b36_left(cutAngle, power) {
  return (
    -3.43382860324e-11 * 1.0 +
    7.10225002143e-08 * (cutAngle) +
    -1.28545097379e-09 * (power) +
    1.85393419663e-06 * (Math.pow(cutAngle, 2)) +
    2.67504142968e-06 * (cutAngle * power) +
    -4.95677551482e-08 * (Math.pow(power, 2)) +
    -8.97145578102e-05 * (Math.pow(cutAngle, 3)) +
    6.98322448152e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000100786175575 * (cutAngle * Math.pow(power, 2)) +
    -1.84360176589e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b36_right(cutAngle, power) {
  return (
    7.27145851817e-09 * 1.0 +
    -4.77770691048e-07 * (cutAngle) +
    2.73937918568e-07 * (power) +
    1.23057344551e-05 * (Math.pow(cutAngle, 2)) +
    -1.80048167883e-05 * (cutAngle * power) +
    1.03180182165e-05 * (Math.pow(power, 2)) +
    -0.000108168525914 * (Math.pow(cutAngle, 3)) +
    0.000462940130136 * (Math.pow(cutAngle, 2) * power) +
    -0.000677932875958 * (cutAngle * Math.pow(power, 2)) +
    0.000388614177158 * (Math.pow(power, 3))
  );
}

// Bracket 37: power in [38.0, 39.0) (n=296, split=25, rmse=0.6688)
function __predictAngleError_b37_left(cutAngle, power) {
  return (
    2.56281706007e-13 * 1.0 +
    5.40069202741e-08 * (cutAngle) +
    9.96741041158e-12 * (power) +
    9.75828041638e-08 * (Math.pow(cutAngle, 2)) +
    2.08926753588e-06 * (cutAngle * power) +
    3.92337519811e-10 * (Math.pow(power, 2)) +
    1.41163036063e-05 * (Math.pow(cutAngle, 3)) +
    3.77627891316e-06 * (Math.pow(cutAngle, 2) * power) +
    8.0824738305e-05 * (cutAngle * Math.pow(power, 2)) +
    1.0877257812e-08 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b37_right(cutAngle, power) {
  return (
    5.52206634057e-10 * 1.0 +
    8.58098875689e-08 * (cutAngle) +
    2.14485011204e-08 * (power) +
    -3.85537791986e-06 * (Math.pow(cutAngle, 2)) +
    3.31313269435e-06 * (cutAngle * power) +
    8.33592145869e-07 * (Math.pow(power, 2)) +
    3.87514946213e-05 * (Math.pow(cutAngle, 3)) +
    -0.000149296012547 * (Math.pow(cutAngle, 2) * power) +
    0.000128252098162 * (cutAngle * Math.pow(power, 2)) +
    3.21283674716e-05 * (Math.pow(power, 3))
  );
}

// Bracket 38: power in [39.0, 40.0) (n=296, split=58, rmse=1.3982)
function __predictAngleError_b38_left(cutAngle, power) {
  return (
    -1.10581770863e-10 * 1.0 +
    8.89723057879e-08 * (cutAngle) +
    -4.35031710073e-09 * (power) +
    -1.32515099029e-06 * (Math.pow(cutAngle, 2)) +
    3.53062312984e-06 * (cutAngle * power) +
    -1.72427155961e-07 * (Math.pow(power, 2)) +
    -2.05557867941e-05 * (Math.pow(cutAngle, 3)) +
    -5.26101913909e-05 * (Math.pow(cutAngle, 2) * power) +
    0.000140171958301 * (cutAngle * Math.pow(power, 2)) +
    -6.90356099011e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b38_right(cutAngle, power) {
  return (
    2.77619330166e-08 * 1.0 +
    -1.73498774796e-06 * (cutAngle) +
    1.1021865397e-06 * (power) +
    3.54971106627e-05 * (Math.pow(cutAngle, 2)) +
    -6.88796889888e-05 * (cutAngle * power) +
    4.37715414346e-05 * (Math.pow(power, 2)) +
    -0.000233306357078 * (Math.pow(cutAngle, 3)) +
    0.00141143385248 * (Math.pow(cutAngle, 2) * power) +
    -0.00273585221922 * (cutAngle * Math.pow(power, 2)) +
    0.00173867743533 * (Math.pow(power, 3))
  );
}

// Bracket 39: power in [40.0, 41.0) (n=296, split=52, rmse=1.3666)
function __predictAngleError_b39_left(cutAngle, power) {
  return (
    -5.62215202441e-11 * 1.0 +
    6.54868154661e-08 * (cutAngle) +
    -2.27464973773e-09 * (power) +
    -1.9322094568e-07 * (Math.pow(cutAngle, 2)) +
    2.66766657025e-06 * (cutAngle * power) +
    -9.29985523864e-08 * (Math.pow(power, 2)) +
    -4.83704425456e-05 * (Math.pow(cutAngle, 3)) +
    -7.88561015861e-06 * (Math.pow(cutAngle, 2) * power) +
    0.000108655502358 * (cutAngle * Math.pow(power, 2)) +
    -3.76110338685e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b39_right(cutAngle, power) {
  return (
    1.98989670046e-09 * 1.0 +
    -6.22837548727e-08 * (cutAngle) +
    8.10437744855e-08 * (power) +
    6.71823798361e-07 * (Math.pow(cutAngle, 2)) +
    -2.53634021501e-06 * (cutAngle * power) +
    3.29736165629e-06 * (Math.pow(power, 2)) +
    -9.75739135531e-06 * (Math.pow(cutAngle, 3)) +
    2.72672013272e-05 * (Math.pow(cutAngle, 2) * power) +
    -0.000103310770582 * (cutAngle * Math.pow(power, 2)) +
    0.00013434860891 * (Math.pow(power, 3))
  );
}

// Bracket 40: power in [41.0, 42.0) (n=296, split=28, rmse=1.5148)
function __predictAngleError_b40_left(cutAngle, power) {
  return (
    7.2324212517e-12 * 1.0 +
    3.95434530604e-08 * (cutAngle) +
    2.97638477632e-10 * (power) +
    8.89811069314e-07 * (Math.pow(cutAngle, 2)) +
    1.65065428738e-06 * (cutAngle * power) +
    1.25491850275e-08 * (Math.pow(power, 2)) +
    -1.30992342858e-05 * (Math.pow(cutAngle, 3)) +
    3.71405297163e-05 * (Math.pow(cutAngle, 2) * power) +
    6.88982275493e-05 * (cutAngle * Math.pow(power, 2)) +
    5.10420295615e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b40_right(cutAngle, power) {
  return (
    5.74204240413e-10 * 1.0 +
    4.29514295409e-08 * (cutAngle) +
    2.40438771789e-08 * (power) +
    -2.04514991955e-06 * (Math.pow(cutAngle, 2)) +
    1.79378770958e-06 * (cutAngle * power) +
    1.0044752092e-06 * (Math.pow(power, 2)) +
    1.93989958094e-05 * (Math.pow(cutAngle, 3)) +
    -8.52069842801e-05 * (Math.pow(cutAngle, 2) * power) +
    7.47953157516e-05 * (cutAngle * Math.pow(power, 2)) +
    4.17797352172e-05 * (Math.pow(power, 3))
  );
}

// Bracket 41: power in [42.0, 43.0) (n=296, split=29, rmse=1.4072)
function __predictAngleError_b41_left(cutAngle, power) {
  return (
    8.35141014252e-13 * 1.0 +
    4.04721212422e-08 * (cutAngle) +
    4.20884859989e-11 * (power) +
    2.26888791668e-07 * (Math.pow(cutAngle, 2)) +
    1.73057534309e-06 * (cutAngle * power) +
    1.86460726803e-09 * (Math.pow(power, 2)) +
    7.80225414038e-06 * (Math.pow(cutAngle, 3)) +
    9.70183979309e-06 * (Math.pow(cutAngle, 2) * power) +
    7.40040617173e-05 * (cutAngle * Math.pow(power, 2)) +
    6.62575519225e-08 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b41_right(cutAngle, power) {
  return (
    -1.07513297821e-11 * 1.0 +
    9.98064562079e-08 * (cutAngle) +
    -4.79965689882e-10 * (power) +
    -4.23345526332e-06 * (Math.pow(cutAngle, 2)) +
    4.27115062376e-06 * (cutAngle * power) +
    -2.27592110535e-08 * (Math.pow(power, 2)) +
    4.6359847361e-05 * (Math.pow(cutAngle, 3)) +
    -0.000180467644975 * (Math.pow(cutAngle, 2) * power) +
    0.000182466067375 * (cutAngle * Math.pow(power, 2)) +
    -8.79760218951e-07 * (Math.pow(power, 3))
  );
}

// Bracket 42: power in [43.0, 44.0) (n=296, split=29, rmse=1.1645)
function __predictAngleError_b42_left(cutAngle, power) {
  return (
    9.09900263946e-12 * 1.0 +
    2.7362304899e-08 * (cutAngle) +
    3.98689978609e-10 * (power) +
    1.43184607537e-06 * (Math.pow(cutAngle, 2)) +
    1.19796276047e-06 * (cutAngle * power) +
    1.74055427485e-08 * (Math.pow(power, 2)) +
    -5.10145333595e-05 * (Math.pow(cutAngle, 3)) +
    6.2683069669e-05 * (Math.pow(cutAngle, 2) * power) +
    5.24447069466e-05 * (cutAngle * Math.pow(power, 2)) +
    7.66999505949e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b42_right(cutAngle, power) {
  return (
    3.38837558394e-10 * 1.0 +
    4.65312669566e-08 * (cutAngle) +
    1.47599372755e-08 * (power) +
    -2.51288300123e-06 * (Math.pow(cutAngle, 2)) +
    2.03948319114e-06 * (cutAngle * power) +
    6.45891250885e-07 * (Math.pow(power, 2)) +
    2.43581826229e-05 * (Math.pow(cutAngle, 3)) +
    -0.000110126600666 * (Math.pow(cutAngle, 2) * power) +
    8.90608055629e-05 * (cutAngle * Math.pow(power, 2)) +
    2.84038341314e-05 * (Math.pow(power, 3))
  );
}

// Bracket 43: power in [44.0, 45.0) (n=296, split=29, rmse=1.6812)
function __predictAngleError_b43_left(cutAngle, power) {
  return (
    6.42911898175e-12 * 1.0 +
    2.87977188851e-08 * (cutAngle) +
    2.82594890643e-10 * (power) +
    1.09795651937e-06 * (Math.pow(cutAngle, 2)) +
    1.29003490771e-06 * (cutAngle * power) +
    1.30915674673e-08 * (Math.pow(power, 2)) +
    -4.1879456917e-05 * (Math.pow(cutAngle, 3)) +
    4.9184717096e-05 * (Math.pow(cutAngle, 2) * power) +
    5.77865334836e-05 * (cutAngle * Math.pow(power, 2)) +
    5.80253318296e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b43_right(cutAngle, power) {
  return (
    6.61056254727e-10 * 1.0 +
    -1.54312268536e-08 * (cutAngle) +
    2.95355070368e-08 * (power) +
    7.38401989032e-07 * (Math.pow(cutAngle, 2)) +
    -6.91952160555e-07 * (cutAngle * power) +
    1.32250638847e-06 * (Math.pow(power, 2)) +
    -2.47941094844e-05 * (Math.pow(cutAngle, 3)) +
    3.2991165422e-05 * (Math.pow(cutAngle, 2) * power) +
    -3.09065856837e-05 * (cutAngle * Math.pow(power, 2)) +
    5.93745088334e-05 * (Math.pow(power, 3))
  );
}

// Bracket 44: power in [45.0, 46.0) (n=296, split=41, rmse=0.3909)
function __predictAngleError_b44_left(cutAngle, power) {
  return (
    1.84409038283e-11 * 1.0 +
    9.27313018151e-09 * (cutAngle) +
    8.59223041881e-10 * (power) +
    3.78614055335e-06 * (Math.pow(cutAngle, 2)) +
    4.25304338829e-07 * (cutAngle * power) +
    4.00093310743e-08 * (Math.pow(power, 2)) +
    -0.000189190922239 * (Math.pow(cutAngle, 3)) +
    0.000173489860322 * (Math.pow(cutAngle, 2) * power) +
    1.94782948018e-05 * (cutAngle * Math.pow(power, 2)) +
    1.7621898589e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b44_right(cutAngle, power) {
  return (
    -5.42371601495e-09 * 1.0 +
    7.23443149037e-07 * (cutAngle) +
    -2.48864130993e-07 * (power) +
    -2.92302483545e-05 * (Math.pow(cutAngle, 2)) +
    3.31904425426e-05 * (cutAngle * power) +
    -1.13969085985e-05 * (Math.pow(power, 2)) +
    0.000364750090142 * (Math.pow(cutAngle, 3)) +
    -0.00134173237964 * (Math.pow(cutAngle, 2) * power) +
    0.00151800920797 * (cutAngle * Math.pow(power, 2)) +
    -0.000520638195976 * (Math.pow(power, 3))
  );
}

// Bracket 45: power in [46.0, 47.0) (n=296, split=37, rmse=1.1799)
function __predictAngleError_b45_left(cutAngle, power) {
  return (
    2.3633728817e-11 * 1.0 +
    3.26406399707e-09 * (cutAngle) +
    1.11980444612e-09 * (power) +
    4.66935872094e-06 * (Math.pow(cutAngle, 2)) +
    1.52505827188e-07 * (cutAngle * power) +
    5.21292250647e-08 * (Math.pow(power, 2)) +
    -0.000234524380481 * (Math.pow(cutAngle, 3)) +
    0.000218663621335 * (Math.pow(cutAngle, 2) * power) +
    7.16357155463e-06 * (cutAngle * Math.pow(power, 2)) +
    2.39834950534e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b45_right(cutAngle, power) {
  return (
    -1.13756662423e-09 * 1.0 +
    2.0006009171e-07 * (cutAngle) +
    -5.35817798756e-08 * (power) +
    -8.5136294754e-06 * (Math.pow(cutAngle, 2)) +
    9.3718284896e-06 * (cutAngle * power) +
    -2.5317174181e-06 * (Math.pow(power, 2)) +
    0.000101435781543 * (Math.pow(cutAngle, 3)) +
    -0.000400084179169 * (Math.pow(cutAngle, 2) * power) +
    0.000439258617795 * (cutAngle * Math.pow(power, 2)) +
    -0.000118267832495 * (Math.pow(power, 3))
  );
}

// Bracket 46: power in [47.0, 48.0) (n=296, split=42, rmse=0.3152)
function __predictAngleError_b46_left(cutAngle, power) {
  return (
    1.25925833555e-11 * 1.0 +
    8.47839321966e-09 * (cutAngle) +
    5.78831270689e-10 * (power) +
    3.32950766731e-06 * (Math.pow(cutAngle, 2)) +
    4.05827467686e-07 * (cutAngle * power) +
    2.83219961911e-08 * (Math.pow(power, 2)) +
    -0.000182022307784 * (Math.pow(cutAngle, 3)) +
    0.000159364318968 * (Math.pow(cutAngle, 2) * power) +
    1.94021092913e-05 * (cutAngle * Math.pow(power, 2)) +
    1.3694927049e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b46_right(cutAngle, power) {
  return (
    -8.93679859927e-09 * 1.0 +
    1.19547754274e-06 * (cutAngle) +
    -4.29828702691e-07 * (power) +
    -5.02926534436e-05 * (Math.pow(cutAngle, 2)) +
    5.71112845672e-05 * (cutAngle * power) +
    -2.05267481323e-05 * (Math.pow(power, 2)) +
    0.000667171693116 * (Math.pow(cutAngle, 3)) +
    -0.00240430267462 * (Math.pow(cutAngle, 2) * power) +
    0.00273331561415 * (cutAngle * Math.pow(power, 2)) +
    -0.000980063567802 * (Math.pow(power, 3))
  );
}

// Bracket 47: power in [48.0, 49.0) (n=296, split=38, rmse=1.3154)
function __predictAngleError_b47_left(cutAngle, power) {
  return (
    1.62544719665e-11 * 1.0 +
    4.2924881049e-09 * (cutAngle) +
    7.91354821192e-10 * (power) +
    3.90547609117e-06 * (Math.pow(cutAngle, 2)) +
    2.09404815478e-07 * (cutAngle * power) +
    3.92389591188e-08 * (Math.pow(power, 2)) +
    -0.000214108293003 * (Math.pow(cutAngle, 3)) +
    0.000190856639905 * (Math.pow(cutAngle, 2) * power) +
    1.02190886589e-05 * (cutAngle * Math.pow(power, 2)) +
    1.90385874308e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b47_right(cutAngle, power) {
  return (
    -2.2149993032e-09 * 1.0 +
    3.36659759117e-07 * (cutAngle) +
    -1.0900902848e-07 * (power) +
    -1.44602124033e-05 * (Math.pow(cutAngle, 2)) +
    1.6408943676e-05 * (cutAngle * power) +
    -5.34318851181e-06 * (Math.pow(power, 2)) +
    0.000184924850311 * (Math.pow(cutAngle, 3)) +
    -0.000706776057941 * (Math.pow(cutAngle, 2) * power) +
    0.00080425170279 * (cutAngle * Math.pow(power, 2)) +
    -0.000263216058793 * (Math.pow(power, 3))
  );
}

// Bracket 48: power in [49.0, 50.0) (n=296, split=53, rmse=0.7820)
function __predictAngleError_b48_left(cutAngle, power) {
  return (
    -1.31585587951e-11 * 1.0 +
    2.44800672409e-08 * (cutAngle) +
    -6.38418881321e-10 * (power) +
    3.30713190625e-07 * (Math.pow(cutAngle, 2)) +
    1.2207146349e-06 * (cutAngle * power) +
    -3.20373821119e-08 * (Math.pow(power, 2)) +
    -6.78057740495e-05 * (Math.pow(cutAngle, 3)) +
    1.64817379529e-05 * (Math.pow(cutAngle, 2) * power) +
    6.08702015257e-05 * (cutAngle * Math.pow(power, 2)) +
    -1.607394203e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b48_right(cutAngle, power) {
  return (
    2.29155531158e-09 * 1.0 +
    -3.06670025905e-08 * (cutAngle) +
    1.14198664331e-07 * (power) +
    -7.2459553786e-06 * (Math.pow(cutAngle, 2)) +
    -1.52997381122e-06 * (cutAngle * power) +
    5.70690819862e-06 * (Math.pow(power, 2)) +
    0.000181305862444 * (Math.pow(cutAngle, 3)) +
    -0.000361413450587 * (Math.pow(cutAngle, 2) * power) +
    -7.60998823565e-05 * (cutAngle * Math.pow(power, 2)) +
    0.000284495029544 * (Math.pow(power, 3))
  );
}

// Bracket 49: power in [50.0, 51.0) (n=296, split=16, rmse=1.4732)
function __predictAngleError_b49_left(cutAngle, power) {
  return (
    3.61274449026e-12 * 1.0 +
    1.40476404873e-08 * (cutAngle) +
    1.84609062672e-10 * (power) +
    3.55854410525e-06 * (Math.pow(cutAngle, 2)) +
    7.15125147374e-07 * (cutAngle * power) +
    9.34700221121e-09 * (Math.pow(power, 2)) +
    -0.000424474093954 * (Math.pow(cutAngle, 3)) +
    0.00018115627153 * (Math.pow(cutAngle, 2) * power) +
    3.64052257606e-05 * (cutAngle * Math.pow(power, 2)) +
    4.7558637187e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b49_right(cutAngle, power) {
  return (
    -2.42746900253e-10 * 1.0 +
    8.93411973286e-08 * (cutAngle) +
    -1.2059434861e-08 * (power) +
    -5.20630907519e-06 * (Math.pow(cutAngle, 2)) +
    4.5512514005e-06 * (cutAngle * power) +
    -6.07278374348e-07 * (Math.pow(power, 2)) +
    8.99137590444e-05 * (Math.pow(cutAngle, 3)) +
    -0.000264286297456 * (Math.pow(cutAngle, 2) * power) +
    0.000231318475678 * (cutAngle * Math.pow(power, 2)) +
    -3.16315593065e-05 * (Math.pow(power, 3))
  );
}

// Bracket 50: power in [51.0, 52.0) (n=296, split=35, rmse=1.5612)
function __predictAngleError_b50_left(cutAngle, power) {
  return (
    1.61997375185e-11 * 1.0 +
    3.57545700457e-10 * (cutAngle) +
    8.34951887915e-10 * (power) +
    4.24428707901e-06 * (Math.pow(cutAngle, 2)) +
    1.923246298e-08 * (cutAngle * power) +
    4.27323659373e-08 * (Math.pow(power, 2)) +
    -0.000252702129714 * (Math.pow(cutAngle, 3)) +
    0.000220386797375 * (Math.pow(cutAngle, 2) * power) +
    9.83398608815e-07 * (cutAngle * Math.pow(power, 2)) +
    2.26473806046e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b50_right(cutAngle, power) {
  return (
    -1.67121343602e-11 * 1.0 +
    5.83417946207e-08 * (cutAngle) +
    -7.30722057318e-10 * (power) +
    -4.5410391518e-06 * (Math.pow(cutAngle, 2)) +
    3.02297481305e-06 * (cutAngle * power) +
    -4.28885913075e-08 * (Math.pow(power, 2)) +
    9.33611809614e-05 * (Math.pow(cutAngle, 3)) +
    -0.00023549772143 * (Math.pow(cutAngle, 2) * power) +
    0.000156726744229 * (cutAngle * Math.pow(power, 2)) +
    -1.88876269108e-06 * (Math.pow(power, 3))
  );
}

// Bracket 51: power in [52.0, 53.0) (n=296, split=17, rmse=1.5514)
function __predictAngleError_b51_left(cutAngle, power) {
  return (
    1.1421755658e-12 * 1.0 +
    1.57815910539e-08 * (cutAngle) +
    6.07782914225e-11 * (power) +
    1.18908938727e-06 * (Math.pow(cutAngle, 2)) +
    8.35537052564e-07 * (cutAngle * power) +
    3.15358781005e-09 * (Math.pow(power, 2)) +
    -0.000119236999011 * (Math.pow(cutAngle, 3)) +
    6.29556475752e-05 * (Math.pow(cutAngle, 2) * power) +
    4.42369570327e-05 * (cutAngle * Math.pow(power, 2)) +
    1.74124648593e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b51_right(cutAngle, power) {
  return (
    -3.57090008293e-10 * 1.0 +
    1.1781516259e-07 * (cutAngle) +
    -1.97037796231e-08 * (power) +
    -7.68970761776e-06 * (Math.pow(cutAngle, 2)) +
    6.24787894806e-06 * (cutAngle * power) +
    -1.04608314262e-06 * (Math.pow(power, 2)) +
    0.000152649118131 * (Math.pow(cutAngle, 3)) +
    -0.000406469144991 * (Math.pow(cutAngle, 2) * power) +
    0.000329414620571 * (cutAngle * Math.pow(power, 2)) +
    -5.38461234578e-05 * (Math.pow(power, 3))
  );
}

// Bracket 52: power in [53.0, 54.0) (n=296, split=42, rmse=1.1835)
function __predictAngleError_b52_left(cutAngle, power) {
  return (
    9.35589155771e-12 * 1.0 +
    7.36568622116e-09 * (cutAngle) +
    4.76387600991e-10 * (power) +
    2.90344973536e-06 * (Math.pow(cutAngle, 2)) +
    3.96955950725e-07 * (cutAngle * power) +
    2.50111963123e-08 * (Math.pow(power, 2)) +
    -0.000186392517986 * (Math.pow(cutAngle, 3)) +
    0.000156703838736 * (Math.pow(cutAngle, 2) * power) +
    2.14655349397e-05 * (cutAngle * Math.pow(power, 2)) +
    1.32880790977e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b52_right(cutAngle, power) {
  return (
    7.49161649028e-11 * 1.0 +
    1.38861382423e-08 * (cutAngle) +
    4.04703085405e-09 * (power) +
    -5.88214076552e-07 * (Math.pow(cutAngle, 2)) +
    7.52859966426e-07 * (cutAngle * power) +
    2.15556161516e-07 * (Math.pow(power, 2)) +
    6.10253040109e-06 * (Math.pow(cutAngle, 3)) +
    -3.173546472e-05 * (Math.pow(cutAngle, 2) * power) +
    4.05680656156e-05 * (cutAngle * Math.pow(power, 2)) +
    1.17373422855e-05 * (Math.pow(power, 3))
  );
}

// Bracket 53: power in [54.0, 55.0) (n=296, split=15, rmse=1.8411)
function __predictAngleError_b53_left(cutAngle, power) {
  return (
    1.46689689721e-12 * 1.0 +
    1.17541139504e-08 * (cutAngle) +
    8.10980669687e-11 * (power) +
    1.95301312784e-06 * (Math.pow(cutAngle, 2)) +
    6.462686263e-07 * (cutAngle * power) +
    4.50614035123e-09 * (Math.pow(power, 2)) +
    -0.000270750065763 * (Math.pow(cutAngle, 3)) +
    0.000107379412189 * (Math.pow(cutAngle, 2) * power) +
    3.55315623752e-05 * (cutAngle * Math.pow(power, 2)) +
    2.42788962612e-07 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b53_right(cutAngle, power) {
  return (
    -1.61103185122e-10 * 1.0 +
    6.22875100443e-08 * (cutAngle) +
    -8.72724849131e-09 * (power) +
    -4.0100757906e-06 * (Math.pow(cutAngle, 2)) +
    3.41962391273e-06 * (cutAngle * power) +
    -4.62455543139e-07 * (Math.pow(power, 2)) +
    6.8746445791e-05 * (Math.pow(cutAngle, 3)) +
    -0.000222025879208 * (Math.pow(cutAngle, 2) * power) +
    0.000188672641437 * (cutAngle * Math.pow(power, 2)) +
    -2.45132057954e-05 * (Math.pow(power, 3))
  );
}

// Bracket 54: power in [55.0, 56.000000001) (n=296, split=35, rmse=1.2524)
function __predictAngleError_b54_left(cutAngle, power) {
  return (
    7.86526774062e-12 * 1.0 +
    3.66833486673e-09 * (cutAngle) +
    4.43114028387e-10 * (power) +
    2.98418849665e-06 * (Math.pow(cutAngle, 2)) +
    2.05370188698e-07 * (cutAngle * power) +
    2.48459622192e-08 * (Math.pow(power, 2)) +
    -0.000206937261246 * (Math.pow(cutAngle, 3)) +
    0.000167113657554 * (Math.pow(cutAngle, 2) * power) +
    1.14969568947e-05 * (cutAngle * Math.pow(power, 2)) +
    1.40436739149e-06 * (Math.pow(power, 3))
  );
}

function __predictAngleError_b54_right(cutAngle, power) {
  return (
    1.91097861338e-10 * 1.0 +
    -1.97388099453e-09 * (cutAngle) +
    1.07030434831e-08 * (power) +
    -4.66393460516e-07 * (Math.pow(cutAngle, 2)) +
    -1.10897720941e-07 * (cutAngle * power) +
    5.99190547133e-07 * (Math.pow(power, 2)) +
    1.51187006659e-05 * (Math.pow(cutAngle, 3)) +
    -2.61406829575e-05 * (Math.pow(cutAngle, 2) * power) +
    -6.22637567008e-06 * (cutAngle * Math.pow(power, 2)) +
    3.35712434257e-05 * (Math.pow(power, 3))
  );
}

/**
 * Predict the angle error for a shot
 * @param {number} cutAngle - Cut angle in degrees (0 = straight, 90 = max)
 * @param {number} spinY - Vertical spin (-1 to 1, positive = topspin)
 * @param {number} power - Shot power
 * @returns {number} Predicted angle error in degrees
 */
function predictAngleError(cutAngle, spinY, power) {
  // basic input sanitization (avoid NaN/Infinity propagating)
  if (!Number.isFinite(cutAngle) || !Number.isFinite(spinY) || !Number.isFinite(power)) return 0;

  // NOTE: spinY is accepted for compatibility but not used by this model.

  if (power >= 1.0 && power < 2.0) {
    const split = 31;
    let y = (cutAngle < split)
      ? __predictAngleError_b0_left(cutAngle, power)
      : __predictAngleError_b0_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 2.0 && power < 3.0) {
    const split = 30;
    let y = (cutAngle < split)
      ? __predictAngleError_b1_left(cutAngle, power)
      : __predictAngleError_b1_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 3.0 && power < 4.0) {
    const split = 31;
    let y = (cutAngle < split)
      ? __predictAngleError_b2_left(cutAngle, power)
      : __predictAngleError_b2_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 4.0 && power < 5.0) {
    const split = 29;
    let y = (cutAngle < split)
      ? __predictAngleError_b3_left(cutAngle, power)
      : __predictAngleError_b3_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 5.0 && power < 6.0) {
    const split = 30;
    let y = (cutAngle < split)
      ? __predictAngleError_b4_left(cutAngle, power)
      : __predictAngleError_b4_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 6.0 && power < 7.0) {
    const split = 30;
    let y = (cutAngle < split)
      ? __predictAngleError_b5_left(cutAngle, power)
      : __predictAngleError_b5_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 7.0 && power < 8.0) {
    const split = 30;
    let y = (cutAngle < split)
      ? __predictAngleError_b6_left(cutAngle, power)
      : __predictAngleError_b6_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 8.0 && power < 9.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b7_left(cutAngle, power)
      : __predictAngleError_b7_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 9.0 && power < 10.0) {
    const split = 30;
    let y = (cutAngle < split)
      ? __predictAngleError_b8_left(cutAngle, power)
      : __predictAngleError_b8_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 10.0 && power < 11.0) {
    const split = 33;
    let y = (cutAngle < split)
      ? __predictAngleError_b9_left(cutAngle, power)
      : __predictAngleError_b9_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 11.0 && power < 12.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b10_left(cutAngle, power)
      : __predictAngleError_b10_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 12.0 && power < 13.0) {
    const split = 27;
    let y = (cutAngle < split)
      ? __predictAngleError_b11_left(cutAngle, power)
      : __predictAngleError_b11_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 13.0 && power < 14.0) {
    const split = 42;
    let y = (cutAngle < split)
      ? __predictAngleError_b12_left(cutAngle, power)
      : __predictAngleError_b12_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 14.0 && power < 15.0) {
    const split = 51;
    let y = (cutAngle < split)
      ? __predictAngleError_b13_left(cutAngle, power)
      : __predictAngleError_b13_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 15.0 && power < 16.0) {
    const split = 27;
    let y = (cutAngle < split)
      ? __predictAngleError_b14_left(cutAngle, power)
      : __predictAngleError_b14_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 16.0 && power < 17.0) {
    const split = 27;
    let y = (cutAngle < split)
      ? __predictAngleError_b15_left(cutAngle, power)
      : __predictAngleError_b15_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 17.0 && power < 18.0) {
    const split = 48;
    let y = (cutAngle < split)
      ? __predictAngleError_b16_left(cutAngle, power)
      : __predictAngleError_b16_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 18.0 && power < 19.0) {
    const split = 31;
    let y = (cutAngle < split)
      ? __predictAngleError_b17_left(cutAngle, power)
      : __predictAngleError_b17_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 19.0 && power < 20.0) {
    const split = 46;
    let y = (cutAngle < split)
      ? __predictAngleError_b18_left(cutAngle, power)
      : __predictAngleError_b18_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 20.0 && power < 21.0) {
    const split = 12;
    let y = (cutAngle < split)
      ? __predictAngleError_b19_left(cutAngle, power)
      : __predictAngleError_b19_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 21.0 && power < 22.0) {
    const split = 29;
    let y = (cutAngle < split)
      ? __predictAngleError_b20_left(cutAngle, power)
      : __predictAngleError_b20_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 22.0 && power < 23.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b21_left(cutAngle, power)
      : __predictAngleError_b21_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 23.0 && power < 24.0) {
    const split = 27;
    let y = (cutAngle < split)
      ? __predictAngleError_b22_left(cutAngle, power)
      : __predictAngleError_b22_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 24.0 && power < 25.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b23_left(cutAngle, power)
      : __predictAngleError_b23_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 25.0 && power < 26.0) {
    const split = 22;
    let y = (cutAngle < split)
      ? __predictAngleError_b24_left(cutAngle, power)
      : __predictAngleError_b24_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 26.0 && power < 27.0) {
    const split = 31;
    let y = (cutAngle < split)
      ? __predictAngleError_b25_left(cutAngle, power)
      : __predictAngleError_b25_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 27.0 && power < 28.0) {
    const split = 46;
    let y = (cutAngle < split)
      ? __predictAngleError_b26_left(cutAngle, power)
      : __predictAngleError_b26_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 28.0 && power < 29.0) {
    const split = 35;
    let y = (cutAngle < split)
      ? __predictAngleError_b27_left(cutAngle, power)
      : __predictAngleError_b27_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 29.0 && power < 30.0) {
    const split = 40;
    let y = (cutAngle < split)
      ? __predictAngleError_b28_left(cutAngle, power)
      : __predictAngleError_b28_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 30.0 && power < 31.0) {
    const split = 46;
    let y = (cutAngle < split)
      ? __predictAngleError_b29_left(cutAngle, power)
      : __predictAngleError_b29_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 31.0 && power < 32.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b30_left(cutAngle, power)
      : __predictAngleError_b30_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 32.0 && power < 33.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b31_left(cutAngle, power)
      : __predictAngleError_b31_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 33.0 && power < 34.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b32_left(cutAngle, power)
      : __predictAngleError_b32_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 34.0 && power < 35.0) {
    const split = 29;
    let y = (cutAngle < split)
      ? __predictAngleError_b33_left(cutAngle, power)
      : __predictAngleError_b33_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 35.0 && power < 36.0) {
    const split = 53;
    let y = (cutAngle < split)
      ? __predictAngleError_b34_left(cutAngle, power)
      : __predictAngleError_b34_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 36.0 && power < 37.0) {
    const split = 51;
    let y = (cutAngle < split)
      ? __predictAngleError_b35_left(cutAngle, power)
      : __predictAngleError_b35_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 37.0 && power < 38.0) {
    const split = 50;
    let y = (cutAngle < split)
      ? __predictAngleError_b36_left(cutAngle, power)
      : __predictAngleError_b36_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 38.0 && power < 39.0) {
    const split = 25;
    let y = (cutAngle < split)
      ? __predictAngleError_b37_left(cutAngle, power)
      : __predictAngleError_b37_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 39.0 && power < 40.0) {
    const split = 58;
    let y = (cutAngle < split)
      ? __predictAngleError_b38_left(cutAngle, power)
      : __predictAngleError_b38_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 40.0 && power < 41.0) {
    const split = 52;
    let y = (cutAngle < split)
      ? __predictAngleError_b39_left(cutAngle, power)
      : __predictAngleError_b39_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 41.0 && power < 42.0) {
    const split = 28;
    let y = (cutAngle < split)
      ? __predictAngleError_b40_left(cutAngle, power)
      : __predictAngleError_b40_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 42.0 && power < 43.0) {
    const split = 29;
    let y = (cutAngle < split)
      ? __predictAngleError_b41_left(cutAngle, power)
      : __predictAngleError_b41_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 43.0 && power < 44.0) {
    const split = 29;
    let y = (cutAngle < split)
      ? __predictAngleError_b42_left(cutAngle, power)
      : __predictAngleError_b42_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 44.0 && power < 45.0) {
    const split = 29;
    let y = (cutAngle < split)
      ? __predictAngleError_b43_left(cutAngle, power)
      : __predictAngleError_b43_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 45.0 && power < 46.0) {
    const split = 41;
    let y = (cutAngle < split)
      ? __predictAngleError_b44_left(cutAngle, power)
      : __predictAngleError_b44_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 46.0 && power < 47.0) {
    const split = 37;
    let y = (cutAngle < split)
      ? __predictAngleError_b45_left(cutAngle, power)
      : __predictAngleError_b45_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 47.0 && power < 48.0) {
    const split = 42;
    let y = (cutAngle < split)
      ? __predictAngleError_b46_left(cutAngle, power)
      : __predictAngleError_b46_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 48.0 && power < 49.0) {
    const split = 38;
    let y = (cutAngle < split)
      ? __predictAngleError_b47_left(cutAngle, power)
      : __predictAngleError_b47_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 49.0 && power < 50.0) {
    const split = 53;
    let y = (cutAngle < split)
      ? __predictAngleError_b48_left(cutAngle, power)
      : __predictAngleError_b48_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 50.0 && power < 51.0) {
    const split = 16;
    let y = (cutAngle < split)
      ? __predictAngleError_b49_left(cutAngle, power)
      : __predictAngleError_b49_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 51.0 && power < 52.0) {
    const split = 35;
    let y = (cutAngle < split)
      ? __predictAngleError_b50_left(cutAngle, power)
      : __predictAngleError_b50_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 52.0 && power < 53.0) {
    const split = 17;
    let y = (cutAngle < split)
      ? __predictAngleError_b51_left(cutAngle, power)
      : __predictAngleError_b51_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 53.0 && power < 54.0) {
    const split = 42;
    let y = (cutAngle < split)
      ? __predictAngleError_b52_left(cutAngle, power)
      : __predictAngleError_b52_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 54.0 && power < 55.0) {
    const split = 15;
    let y = (cutAngle < split)
      ? __predictAngleError_b53_left(cutAngle, power)
      : __predictAngleError_b53_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  else if (power >= 55.0 && power < 56.000000001) {
    const split = 35;
    let y = (cutAngle < split)
      ? __predictAngleError_b54_left(cutAngle, power)
      : __predictAngleError_b54_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  // fallback: clamp to nearest bracket
  if (power < 1.0) {
    const split = 31;
    let y = (cutAngle < split)
      ? __predictAngleError_b0_left(cutAngle, power)
      : __predictAngleError_b0_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
  {
    const split = 35;
    let y = (cutAngle < split)
      ? __predictAngleError_b54_left(cutAngle, power)
      : __predictAngleError_b54_right(cutAngle, power);
    if (y > 15) y = 15;
    else if (y < -15) y = -15;
    return y;
  }
}

/**
 * Calculate aim adjustment to compensate for predicted angle error
 * @param {number} cutAngle - Cut angle in degrees
 * @param {number} spinY - Vertical spin
 * @param {number} power - Shot power
 * @returns {number} Angle adjustment in degrees (subtract from aim)
 */
function calculateAimAdjustment(cutAngle, spinY, power) {
  return predictAngleError(cutAngle, spinY, power);
}

// Model metadata
const ANGLE_MODEL_INFO = {
  modelType: "piecewise_poly_ridge",
  degree: 3,
  clip: 15,
  nSamples: 15505,
  features: ["cutAngle", "spinY", "power"],
  piecewise: {
    brackets: [
      { pmin: 1.0, pmax: 2.0, split: 31, n: 75 },
      { pmin: 2.0, pmax: 3.0, split: 30, n: 75 },
      { pmin: 3.0, pmax: 4.0, split: 31, n: 150 },
      { pmin: 4.0, pmax: 5.0, split: 29, n: 188 },
      { pmin: 5.0, pmax: 6.0, split: 30, n: 225 },
      { pmin: 6.0, pmax: 7.0, split: 30, n: 292 },
      { pmin: 7.0, pmax: 8.0, split: 30, n: 292 },
      { pmin: 8.0, pmax: 9.0, split: 28, n: 296 },
      { pmin: 9.0, pmax: 10.0, split: 30, n: 296 },
      { pmin: 10.0, pmax: 11.0, split: 33, n: 296 },
      { pmin: 11.0, pmax: 12.0, split: 28, n: 296 },
      { pmin: 12.0, pmax: 13.0, split: 27, n: 296 },
      { pmin: 13.0, pmax: 14.0, split: 42, n: 296 },
      { pmin: 14.0, pmax: 15.0, split: 51, n: 296 },
      { pmin: 15.0, pmax: 16.0, split: 27, n: 296 },
      { pmin: 16.0, pmax: 17.0, split: 27, n: 296 },
      { pmin: 17.0, pmax: 18.0, split: 48, n: 296 },
      { pmin: 18.0, pmax: 19.0, split: 31, n: 296 },
      { pmin: 19.0, pmax: 20.0, split: 46, n: 296 },
      { pmin: 20.0, pmax: 21.0, split: 12, n: 296 },
      { pmin: 21.0, pmax: 22.0, split: 29, n: 296 },
      { pmin: 22.0, pmax: 23.0, split: 28, n: 296 },
      { pmin: 23.0, pmax: 24.0, split: 27, n: 296 },
      { pmin: 24.0, pmax: 25.0, split: 28, n: 296 },
      { pmin: 25.0, pmax: 26.0, split: 22, n: 296 },
      { pmin: 26.0, pmax: 27.0, split: 31, n: 296 },
      { pmin: 27.0, pmax: 28.0, split: 46, n: 296 },
      { pmin: 28.0, pmax: 29.0, split: 35, n: 296 },
      { pmin: 29.0, pmax: 30.0, split: 40, n: 296 },
      { pmin: 30.0, pmax: 31.0, split: 46, n: 296 },
      { pmin: 31.0, pmax: 32.0, split: 28, n: 296 },
      { pmin: 32.0, pmax: 33.0, split: 28, n: 296 },
      { pmin: 33.0, pmax: 34.0, split: 28, n: 296 },
      { pmin: 34.0, pmax: 35.0, split: 29, n: 296 },
      { pmin: 35.0, pmax: 36.0, split: 53, n: 296 },
      { pmin: 36.0, pmax: 37.0, split: 51, n: 296 },
      { pmin: 37.0, pmax: 38.0, split: 50, n: 296 },
      { pmin: 38.0, pmax: 39.0, split: 25, n: 296 },
      { pmin: 39.0, pmax: 40.0, split: 58, n: 296 },
      { pmin: 40.0, pmax: 41.0, split: 52, n: 296 },
      { pmin: 41.0, pmax: 42.0, split: 28, n: 296 },
      { pmin: 42.0, pmax: 43.0, split: 29, n: 296 },
      { pmin: 43.0, pmax: 44.0, split: 29, n: 296 },
      { pmin: 44.0, pmax: 45.0, split: 29, n: 296 },
      { pmin: 45.0, pmax: 46.0, split: 41, n: 296 },
      { pmin: 46.0, pmax: 47.0, split: 37, n: 296 },
      { pmin: 47.0, pmax: 48.0, split: 42, n: 296 },
      { pmin: 48.0, pmax: 49.0, split: 38, n: 296 },
      { pmin: 49.0, pmax: 50.0, split: 53, n: 296 },
      { pmin: 50.0, pmax: 51.0, split: 16, n: 296 },
      { pmin: 51.0, pmax: 52.0, split: 35, n: 296 },
      { pmin: 52.0, pmax: 53.0, split: 17, n: 296 },
      { pmin: 53.0, pmax: 54.0, split: 42, n: 296 },
      { pmin: 54.0, pmax: 55.0, split: 15, n: 296 },
      { pmin: 55.0, pmax: 56.000000001, split: 35, n: 296 },
    ]
  },
  metrics: {
    rSquared: 0.718294,
    rmse: 0.990989,
    mae: 0.620376
  }
};

// Export for use in modules
if (typeof module !== "undefined" && module.exports) {
  module.exports = { predictAngleError, calculateAimAdjustment, ANGLE_MODEL_INFO };
}
